### ISSUE TITLE
[Feature Request] Ability to have temps display in layer chart graph in job status

### ISSUE THREAD

**Issue by jrsphoto** [Duet3D/DuetWebControl#151]
The Layer Chart is super nice to have but I was wondering if it would be possible to have extruder and bed temps display in the same graph, with temp labels on the right side?   Just a thought.

**Comment by jrsphoto** [comment]
And yep, I am aware that the temps are on a graph of there own, It just seems that you could combine the two graphs, or at least give the end user the option to do that?

**Comment by chrishamm** [comment]
Well, I guess it would possible to keep track of the heater temperatures whenever a layer change occurs.

**Comment by jrsphoto** [comment]
Just saw this Chris.. Thanks for doing this!

**Comment by chrishamm** [comment]
It looks like this was already implemented in a previous DWC version but not displayed in the chart. I'll fix this in the next version.

**Comment by chrishamm** [comment]
Now implemented in 3.4-rc1.
