### ISSUE TITLE
Feature request: G-code preview

### ISSUE THREAD

**Issue by TheBum** [Duet3D/DuetWebControl#153]
I'd like to see a G-code preview similar to the one in OctoPrint. It would help verify you have the G-code uploaded that you thought you did. My workaround now is to download the file from the Duet 2 (Maestro) and load it into Voxelizer, but downloads from the board are really slow.

**Comment by swblum** [comment]
Have a look at this [https://github.com/Sindarius/DWC_GCode_Viewer](url)
It is a good start for what you are trying to accomplish.

**Comment by TheBum** [comment]
I just tried Sindarius's fork of DWC (https://github.com/Sindarius/DuetWebControl) and it works rather well, albeit rather slow to render. Hopefully he'll create a pull request soon to include his changes in chrishamm's repo.

**Comment by chrishamm** [comment]
I'd like to integrate it as a separate plugin but it's great to see there's already a fork with support for it! It's on my TODO list.

**Comment by Sindarius** [comment]
Let me know what I can do to help this along.

**Comment by chrishamm** [comment]
Just a short update: This is planned for DWC 2.1.0.

**Comment by Sindarius** [comment]
> Just a short update: This is planned for DWC 2.1.0.

That's exciting. Looking forward to getting the viewer included as a plugin. I have a few features I am aiming to add to it soon.

**Comment by TheBum** [comment]
Hopefully one of those features is a layer preview so that individual layers can be inspected.

**Comment by DMCShep** [comment]
@chrishamm Er wait, is this referring to a GCode Preview or a plugin system?

> Just a short update: This is planned for DWC 2.1.0.

**Comment by Sindarius** [comment]
Something different than the fork I worked I assume?

**Comment by christophmuellerorg** [comment]
Would be amazing in combination with the new [object cancelation feature](https://github.com/dc42/RepRapFirmware/blob/v3-dev/WHATS_NEW_RRF3.md) just introduced in RRF. Each object could be coloured differently and allow for cancelation through a context menu...

**Comment by RomanLyavin** [comment]
it is very cool if this is implemented. I will wait! Thank you for adding this to your plans.

**Comment by chrishamm** [comment]
Implemented in v3.2, enable the corresponding plugin in Settings -> General -> Plugins.
