### ISSUE TITLE
Extrusion Control

### ISSUE THREAD

**Issue by bhbloom** [Duet3D/DuetWebControl#246]
I am running 2.0.6
Under extrusion Control it has
Mix Ratio
Mix E0 E1 E2 E3

I think I saw on a video it had
Mix ALL E0 E1 E2 E3

2 questions
Can I have the ALL button
What does the mix button do?

**Comment by chrishamm** [comment]
I'll consider adding back the "All" button, until then you can use mixing to achieve the same.

Re the question about the mix button, see [M567](https://duet3d.dozuki.com/Wiki/Gcode#Section_M567_Set_tool_mix_ratios).
