### ISSUE TITLE
Filament Download error

### ISSUE THREAD

**Issue by cdedwards** [Duet3D/DuetWebControl#251]
So I added some new filament types and in order to populate the load.g/unload.g files, I was going to download an old filament type and then upload the files to the new filament. Download fails with an error message. I am using the latest DWC and duet2 firmware.

Failed to download load.g
Unexpected token M in JSON at position 0

**Comment by chrishamm** [comment]
Thanks, I could reproduce this problem and will fix it in v3.1.1.

**Comment by chrishamm** [comment]
Fixed in v3.1.1.
