### ISSUE TITLE
Display bad characters in editor

### ISSUE THREAD

**Issue by dc42** [Duet3D/DuetWebControl#256]
If a config.g  or other system file contains bad characters that prevent the line being parsed, then when editing that file in DWC the editor doesn't show those characters, so there is no indication that anything is wrong. It would be better if the editor displayed something, e.g. the DEL symbol.

[config.g.txt](https://github.com/Duet3D/DuetWebControl/files/4711136/config.g.txt)

**Comment by chrishamm** [comment]
This is already the case in CodeMirror. For testing purposes I replaced the first space with a DEL character (0x7F) and it's displayed correctly:

![image](https://user-images.githubusercontent.com/5919449/151670980-e0ac8664-e4d1-4fe0-a278-6dc2077c8df2.png)

It's difficult to highlight special characters when the on-screen keyboard is enabled, though.
