### ISSUE TITLE
Filament sensor: pause message is displayed on DWC even after being acknowledged in PanelDue 

### ISSUE THREAD

**Issue by joaobarros** [Duet3D/DuetWebControl#282]
DWC will display the filament error message even after acknowledging the event via PanelDue and the printer resuming printing.
UPDATE: the message continues to appear even after the print ended

How to replicate:
- cause a filament sensor event
- acknowledge the event and press RESUME on PanelDue
- connect to DWC and verify filament message is still present (with values of the printer being updated in the background)

Duet Web Control 3.1.1
Board: Duet 2 WiFi (2WiFi)
Firmware: RepRapFirmware for Duet 2 WiFi/Ethernet 3.1.1 (2020-05-19b2)
Duet WiFi Server Version: 1.23

**Comment by chrishamm** [comment]
If the message box disappears on both DWC and PanelDue when it is dimissed on DWC then it is a PanelDue/RRF and no DWC issue. If that is the case, please close this issue again and create a new post on the [forum](https://forum.duet3d.com).
