### ISSUE TITLE
DWC 3.1.1 and LPC-Port running on SBC

### ISSUE THREAD

**Issue by tekknix** [Duet3D/DuetWebControl#283]
Hi,

everything works as on my other Duet Wifi and Duet Maestro but i'm not able to make use of the API.

Therefore i'm not able to make use of automatic Slicer-Upload via Curl.

```
tekknix@HP-ZBook ~ $ curl "http://192.168.178.165/rr_status?type=1" -vv
*   Trying 192.168.178.165:80...
* TCP_NODELAY set
* Connected to 192.168.178.165 (192.168.178.165) port 80 (#0)
> GET /rr_status?type=1 HTTP/1.1
> Host: 192.168.178.165
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Mon, 24 Aug 2020 10:01:58 GMT
< Server: Kestrel
< Content-Length: 0
< 
* Connection #0 to host 192.168.178.165 left intact
```

Even a login will shows up 404 Not Found.

Any ideas where to look at? Or is there some implemenation missing?

Regards
MoS-tekknix

**Comment by chrishamm** [comment]
rr_ requets like in RRF are not supported by DSF. The DWC/SBC connection uses a different connection API so this isn't surprising.

With DSF 3.2 it will be possible to write a plugin that emulates rr_ requests, see https://github.com/Duet3D/DuetSoftwareFramework/issues/99#issuecomment-678758170
