### ISSUE TITLE
Translation to PT-BR

### ISSUE THREAD

**Issue by claytonferraz** [Duet3D/DuetWebControl#285]
How can I contribute with the translation of DuetWebControl into Brazilian Portuguese?

**Comment by chrishamm** [comment]
You need to translate this file: https://github.com/Duet3D/DuetWebControl/blob/v3.2-dev/src/i18n/en.js Be aware that it will be changed again shortly, though.

**Comment by claytonferraz** [comment]
OK, all right, but either way, it’s already a base and should change a few things only.

**Comment by chrishamm** [comment]
3.2.0-beta1 is almost ready and the translations won't be changed any further before I release it. If you decide to provide translations, either
- create a new issue where you provide the resulting file
- make a new pull request
- or send me an email with the translated file attached
