### ISSUE TITLE
3.2.0-b1+2 : plugins in both general and machine-specific tab?

### ISSUE THREAD

**Issue by mydevpeeps** [Duet3D/DuetWebControl#289]
is this intentional? i see the 3 plugins in general, but in machine-specific the plugin list is empty.

**Comment by chrishamm** [comment]
Yes, this is intentional and they will be likely renamed in 3.2-b2.

In Settings -> General you can find built-in plugins and in Settings -> Machine you can find machine-specific third-party plugins.

**Comment by mydevpeeps** [comment]
Thanks so much for explaining! Closing :-P
