### ISSUE TITLE
Since 3.2 b no connection anymore host is allready connected

### ISSUE THREAD

**Issue by Stephan3** [Duet3D/DuetWebControl#293]
Not sure what ecxatly went wrong. Since current 3.2b  

![image](https://user-images.githubusercontent.com/47381132/93798223-9d457180-fc3d-11ea-8fff-a41c6356ce4f.png)

it keeps requesting Status1-2 but webinterface is not accessible. It works till 3.1.1
Is there something special i have to take care of in the future ?

Thanks
Stephan

**Comment by mydevpeeps** [comment]
@Stephan3 can you disable all plugins and try again. That seemed to make the issues go away for me.

**Comment by Stephan3** [comment]
@mydevpeeps i saw your ticket. How to do so without access to webif?
It’s not rrf it’s Klipper.

**Comment by chrishamm** [comment]
I think the reason is a messed up dwc-settings.json file, try to delete it.

Note that the file paths for DWC settings/cache have been changed from '0:/sys/dwc2-settings.json' and '0:/sys/dwc2-cache.json' to '0:/sys/dwc-settings.json' and '0:/sys/dwc-cache.json'.
