### ISSUE TITLE
Odd height map behaviour

### ISSUE THREAD

**Issue by LittleHobbyShop** [Duet3D/DuetWebControl#296]
Running the current 3.2 beta 2

Height map does not refresh when completing a new bed mesh routine.
Refreshing the browser page ~~when height map tab is active~~ results in a black height map window. At this stage inverting Z and then back again seems to restore the view.
Once the view is restored the origin indicator is missing:
![image](https://user-images.githubusercontent.com/16748684/96027788-4d2e8900-0e50-11eb-9a93-a68a9a5ef182.png)

**Comment by chrishamm** [comment]
I believe this is fixed now. At least I could reproduce an issue that prevented the heightmap from being reloaded after a G29 call. It will be fixed in the next beta.
