### ISSUE TITLE
Gcode visualiser showing arcs as straight lines

### ISSUE THREAD

**Issue by LittleHobbyShop** [Duet3D/DuetWebControl#297]
DWC Version 3.2 beta 2
A little difficult to show but the below is a comparison between the DWC viewer and an online gcode viewer. It appears that arcs are shown as straight lines between start and end points.

DWC:
![image](https://user-images.githubusercontent.com/16748684/96029207-3e48d600-0e52-11eb-8626-be9db2babce7.png)
Online Viewer:
![image](https://user-images.githubusercontent.com/16748684/96029286-5c163b00-0e52-11eb-870a-e5c708c8bbee.png)

**Comment by chrishamm** [comment]
DWC 3.2-RC1 will come with a different G-code viewer so I am closing this one.
