### ISSUE TITLE
ToolInput.vue throws exception if a tool has neither heaters nor a spindle

### ISSUE THREAD

**Issue by wilriker** [Duet3D/DuetWebControl#298]
If a tool has neither a heater nor a spindle (e.g. a tool that only carries a touch-probe) it will lead to an exception in `ToolInput.vue` in the `mounted()` function:
```
mounted() {
		this.inputElement = this.$el.querySelector('input');
		if (this.tool) {
			this.actualValue = this.tool[this.active ? 'active' : 'standby'][this.toolHeaterIndex];
			this.inputValue = this.tool[this.active ? 'active' : 'standby'][this.toolHeaterIndex].toString();
```
The last line will throw an exception trying to access `toString()` because the respective `this.tool.active` and `this.tool.standby` arrays will have a length of 0. This is a regression in DWC 3.2 and was handled correctly in 3.1.

**Comment by chrishamm** [comment]
Thanks, it's now fixed on GitHub.
