### ISSUE TITLE
Suggestion: Link to FW Releases in DWC

### ISSUE THREAD

**Issue by dintid** [Duet3D/DuetWebControl#302]
It would be helpfull with a direct link to firmware releases in the DWC in Settings -> General in the Software information box:
Could be named something like "Check for new firmware". Could open web for now and later maybe actually automatically check.
https://github.com/dc42/RepRapFirmware/releases

**Comment by chrishamm** [comment]
Correct, and it's planned to be implemented as a plugin.

**Comment by chrishamm** [comment]
Closing because it's a duplicate of https://github.com/Duet3D/DuetWebControl/issues/187.
