### ISSUE TITLE
Potentially dangerous click-through scenario

### ISSUE THREAD

**Issue by tdcox** [Duet3D/DuetWebControl#305]
Duet Web Control 3.2.0-beta4

On the dashboard page, notifications are displayed over the Macros button panel and are animated. There is an issue where user clicks intended to dismiss notifications can instead end up passing through to the Macro buttons underneath, leading to unintended motion that may be dangerous.

In the past week, I have encountered multiple instances where an attempt to dismiss a notification has instead triggered a Macro, typically initiating a surprise tool change.

In safety-related systems, it should be a general principle that buttons should not be stacked over other active UI components, so as to avoid the risk of event pass-though or mis-aligned aim due to the target moving. This is particularly significant in relation to touch displays where the X/Y contact event may fall unpredictably within a circle of 1cm or so in diameter. 

A 'clear all notifications' button in a safe area of the screen, rather than buttons local to the pop-ups would also be an alternate approach.

**Comment by chrishamm** [comment]
This will be resolved in 3.4-b8, see the referenced issue.
