### ISSUE TITLE
WebControl

### ISSUE THREAD

**Issue by Brezovnik** [Duet3D/DuetWebControl#313]
**Hi all,**
I have a problem that in webContro{duet 2 wifi}l all files are multiplied several times. For example if i create a filament (ABS) I get numerous files named ABS and also in system editor tab all files are multiplied n-times. 
Interface is upgraded to 3.1.1 and firmware is 1.21. 
It is very annoying and if someone has a solution I would appreciate if he/she shares it with me.
[https://1drv.ms/u/s!Ah9nCOxgsIqfhSSWh-vO55SV0qoI](url)

**Comment by chrishamm** [comment]
You are not using DWC 2 or 3, that's still DWC v1 which isn't supported any more. Please use the [forum](https://forum.duet3d.com) for support questions.
