### ISSUE TITLE
Not a issues but a question

### ISSUE THREAD

**Issue by CrazyCreator13** [Duet3D/DuetWebControl#318]
can i use the DWC 3.2 on a Duet 2 with RepRapFirmware for Duet 2 WiFi/Ethernet 2.05.1 (2020-02-09b1)?

**Comment by chrishamm** [comment]
Yes, it should work but I haven't tested v3.2 with RRF v2 yet. In the future please use the [forum](https://forum.duet3d.com) for support questions.
