### ISSUE TITLE
Whitespace Consistency in DWC gcode editor

### ISSUE THREAD

**Issue by T3P3** [Duet3D/DuetWebControl#321]
As highlighted in this post:
https://forum.duet3d.com/topic/20864/dwc-3-2-gcode-editor-issue

Not replacing <tab> characters with (4?) spaces leads to issues with conditional gcode.

**Comment by chrishamm** [comment]
Thanks, this will be fixed in v3.3.

**Comment by chrishamm** [comment]
Already fixed in v3.2.2.
