### ISSUE TITLE
Onscreen Keyboard Hides Bottom of Display

### ISSUE THREAD

**Issue by GoremanX** [Duet3D/DuetWebControl#326]
When editing the very bottom of a file with the onscreen keyboard, the onscreen keyboard covers up the bottom of that file which makes it impossible to know what we're doing.

**Comment by chrishamm** [comment]
Thanks, I can confirm this. I'll fix it in the upcoming v3.2.1.

**Comment by chrishamm** [comment]
Should be fixed now.
