### ISSUE TITLE
Setting temp on the "Control All" dropdown menu sets heatbed temp as well

### ISSUE THREAD

**Issue by Hernicz** [Duet3D/DuetWebControl#329]
Setting temp over 200 degrees in "control all" dropdown menu sets temp for heatbed as well which is not safe with AC bed heaters.

Please fix
Thank yuo

**Comment by chrishamm** [comment]
This is still expected behavior although I guess the facility would be more useful if there were checkboxes for the different heater types (heaters/beds/chambers). I'll change that in v3.3.

**Comment by Hernicz** [comment]
One of the users heated up his heatbed to 230 °C. He claims DWC1 only set Tool Temp by Control All.

A "Control All - Tools only" checkbox in settings would be nice.

Thank you

**Comment by chrishamm** [comment]
DWC 3.3-b2 allows you to set different temperatures per heater type.
