### ISSUE TITLE
Feature Request: allow to load content of settings.js from a file on the SD

### ISSUE THREAD

**Issue by psychotik2k3** [Duet3D/DuetWebControl#331]
It's too bad that if i want to modify the list of feedrates for extruder i have to recompile the whole firmware while changing settings without recompiling is the great stength of RRF.

So it would be great if feed rates and other parameters that are machine specific which are in settings.js could be loaded from the sd card content.

thanks

**Comment by chrishamm** [comment]
Settings can be already changed, the values from settings.js are just presets. You can change the movement steps and extrusion amounts/feedrates by right-clicking on the buttons.

**Comment by psychotik2k3** [comment]
didn't knew. thanks a lot.
