### ISSUE TITLE
Percentage of uploading gcode file is fixed at 100%

### ISSUE THREAD

**Issue by phcella** [Duet3D/DuetWebControl#335]
Hi,

When I upload a gcode file, the percentage of the uploading doesn't change, it is fixed at 100%.
I made a video to show the problem.

https://user-images.githubusercontent.com/20034679/108626843-1f2a0880-7431-11eb-8c69-d5ffb74bf089.mp4

Thanks

**Comment by chrishamm** [comment]
Please use the [forum](https://forum.duet3d.com) for support questions.
