### ISSUE TITLE
Feature Request: AXIS Movement LOCK Button

### ISSUE THREAD

**Issue by sineer** [Duet3D/DuetWebControl#336]
Hello friend,

It's the second time I mess up a print because I accidentally hit an axis movement button :-(

Please add an AXIS LOCK option/button that default to locked while printing :-)

Thanks!

**Comment by chrishamm** [comment]
I don't think it's a good idea to permit custom movements/extrusion during a live print so I'll disable these controls by default in the next version.

**Comment by chrishamm** [comment]
Now implemented in 3.4-rc1.
