### ISSUE TITLE
Prusaslicer direct upload with folders

### ISSUE THREAD

**Issue by nofuturekid** [Duet3D/DuetWebControl#338]
There seems to be a problem with uploading from Prusaslicer when there are folder names the filename.

![image](https://user-images.githubusercontent.com/7026230/110201074-86987d00-7e61-11eb-816b-319cde003fb7.png)

Duet (standalone)
- If the folder already exists everthing is ok
- If the folder is not existing then upload fails with: 
![image](https://user-images.githubusercontent.com/7026230/110201115-bc3d6600-7e61-11eb-89e6-d08ef5fc3257.png)

Duet (with SBC)
- Upload never fails. The file is not put into the correct folder but in the main folder a file with "Folder/Filename.g" is created.
- No matter "Folder" exististed prior uploading or not

**Comment by chrishamm** [comment]
It isn't a bug in DWC so I will close this issue. That problem should be reported on the PrusaSlicer GitHub page instead.

**Comment by nofuturekid** [comment]
If DWC would behave the same while in standalone and while running on SBC I would agree.l, but it's not.
