### ISSUE TITLE
Printduration after print finished

### ISSUE THREAD

**Issue by Stephan3** [Duet3D/DuetWebControl#339]
Dont Know if i am the only one seeing this. Once after a print was finished. the print duration was shown.
Now theres an N/A or a 0s. It worked once

**Comment by chrishamm** [comment]
The last print duration is displayed nicely on my setup:

![image](https://user-images.githubusercontent.com/5919449/116418359-5b685380-a83c-11eb-8716-936af85f69d8.png)

But this is with DWC in SBC connection mode and I suspect it will work equally well in standalone mode with the new rr_model queries. Also bear in mind that v3.3 will be the last version which will retain (partial) support for old-style status requests (i.e. rr_status). Those queries will be dropped from v3.4.
