### ISSUE TITLE
No Layer Count

### ISSUE THREAD

**Issue by CrazyCreator13** [Duet3D/DuetWebControl#342]
The layer count and diagramm not work with the latest version.
![Bildschirmfoto 2021-03-14 um 17 08 51](https://user-images.githubusercontent.com/3821732/111075424-3ae07600-84e8-11eb-9b88-447a868390d7.png)

**Comment by chrishamm** [comment]
It does work but you probably haven't read the upgrade notes yet. The layer recognition has been changed in the latest version so you may need to adjust your slicer to fix it.

Also note that RRF reports the current layer, DWC only displays that.
