### ISSUE TITLE
System Update in mobile View of dwc 33b2 Not possible

### ISSUE THREAD

**Issue by wildblue** [Duet3D/DuetWebControl#344]
To do system updates you have to switch to the Desktop Mode on mobil phones. When the screen-resolution is top small, the dialog to install updates does not appears either.

**Comment by chrishamm** [comment]
Thanks, I could confirm there is an issue with the upload button in xs mode. I'll fix it.

**Comment by chrishamm** [comment]
Fixed in 3.3-b2.

**Comment by bestonephoenix** [comment]
This seems to be the case again in 3.6.0 - when in small resolution (phone), the upload button shows but no upload takes place after selecting a file.
