### ISSUE TITLE
Command history should not be stored to the Duet SD card

### ISSUE THREAD

**Issue by dc42** [Duet3D/DuetWebControl#354]
Unless "Save settings in local storage" is selected, then every time a command is entered in DWC, file dwc-settings.json gets written. This causes excessive wear and fragmentation on the SD card. It would be better if only the settings in Settings/General were written to the SD card, and command history was always saved to browser local storage.

**Comment by chrishamm** [comment]
Good point, I've changed DWC to store the code history in the browser's cache. Recent items appear at the top of the auto-complete list too.
