### ISSUE TITLE
Command history match results in wrong order

### ISSUE THREAD

**Issue by dc42** [Duet3D/DuetWebControl#355]
When I start typing in a command in the console, the matching command history results appear to be sorted alphabetically. When there are a lot of matching results, this often means that the matching command that I typed a few seconds ago (which is the one I want to repeat) does not appear in the list at all because there are too many matches to display them all, whereas a command that I typed several weeks ago is offered. This is most unhelpful.

Suggestion: display the matching commands in most-recently-used order.

**Comment by chrishamm** [comment]
Done, will be changed in the next version.
