### ISSUE TITLE
Tool position coordinates freeze if you have Z probe #2 but not #0

### ISSUE THREAD

**Issue by dc42** [Duet3D/DuetWebControl#357]
If I have no Z probes configured, then I create Z probe #2 using command M559 K2 P8 C"..." then DWC no longer updates the tool position coordinates in the Status panel. The Object Model Browser shows that DWC has the correct coordinates form RRF. My guess is that having Z probe 0 with value "null" confuses DWC.

**Comment by chrishamm** [comment]
Thanks for the report, I've got a fix ready for RC1.
