### ISSUE TITLE
Use M73 for print estimates

### ISSUE THREAD

**Issue by AfroHorse** [Duet3D/DuetWebControl#359]
I have recently begun using RRF/DWC and noticed that the print estimates are taken from the Slicer (among other sources). Due to running bed levelling in the custom GCode of the slicer, I end up with print estimates that are out due to not accounting for that. The slicer does output M73 messages however these are not picked up by DWC from what I can see.

Looking at RRF release notes, it implies that M73s are being processed so I believe this is a feature DWC could add.

**Comment by chrishamm** [comment]
This is already supported by both DWC and RRF but it isn't part of a stable release yet. Please upgrade to software version 3.3-rc1 if you wish to test it.

Estimations by the slicer (as provided by M73 e.g.) are shown in DWC on the "Time Left" -> Slicer panel.
