### ISSUE TITLE
Trying to Open a Accelerometer CSV does Not work

### ISSUE THREAD

**Issue by wildblue** [Duet3D/DuetWebControl#360]
3.3 rc1
The File geht's saved unser /accelerometer, but can't be opened via the machine specific/Accelerometer Tab.

Message is red and says:
Failed to parse CSV file

This appears to happen, when the last line of the CSV does contain the message  "Failed to collect data from accelerometer" is a measurement-line or empty.

If the last line is like "Rate 935, overflows 4" you are promped with a Dialog, missing the text:
   Overflows detected
 
  $t('plugins.accelerometer.overflowPrompt.prompt')

The result is displayed only when you click on yes, whatever this neans ;-)

**Comment by chrishamm** [comment]
The first error message indicates a corrupt CSV file which makes sense if the last message reads `Failed to collect data from accelerometer`. In this case the plugin behaves as expected.

I'll fix the message prompt, thanks for reporting that. It should display something like `This CSV file has reported overflows. Are you sure you wish to continue?` instead.
