### ISSUE TITLE
reprap.htm

### ISSUE THREAD

**Issue by CrazyCreator13** [Duet3D/DuetWebControl#365]
I don't really think it's a mistake, but on purpose.
But I still want to ask: 
Does the reprap.htm file or the design behind it no longer exist?
I liked the old design more

**Comment by CrazyCreator13** [comment]
I use a sbc (raspi pi 4) and can find a index.html in the folder, but in browser I have a 404 error

**Comment by chrishamm** [comment]
DWC1 is not compatible with SBC mode.

If you get a 404 error, it sounds like the file permissions are off. Try running `sudo apt install --reinstall duetwebcontrol` to fix it.

**Comment by CrazyCreator13** [comment]
i use: Duet Web Control 3.3.0-rc2
When I try: http://ccc.local/index.html I see this:

![Bildschirmfoto 2021-05-17 um 22 33 43](https://user-images.githubusercontent.com/3821732/118552962-f1b6d780-b75f-11eb-8fe5-9d7f18cd3314.png)
