### ISSUE TITLE
MCU temperature sensor min/max is wrong

### ISSUE THREAD

**Issue by Lyr3x** [Duet3D/DuetWebControl#371]
Looking at the MCU temperature attribute, I realized that at least the max value is not correct. Not a big deal but might be worth fixing. Refresh does not change the value.

![image](https://user-images.githubusercontent.com/6078365/123270069-d928a280-d4ff-11eb-9c80-26e49acb53f6.png)

**Comment by chrishamm** [comment]
Thanks for the report, we'll fix this in RRF.

**Comment by Lyr3x** [comment]
I was not sure if its only "frontend" related or if the fw reports wrong values. New to the the RRF world 👍
