### ISSUE TITLE
[FeatureRequest]: Thumbnail during printing

### ISSUE THREAD

**Issue by bttguy** [Duet3D/DuetWebControl#382]
### Is your feature request related to a problem? Please describe.

It is just a nice touch rather than a resolveable problem,

### Describe the solution you propose.

I would like to ask wether it is possible to implement a thumbnail image on the status page during printing?
Since most of the slicers can generate a thumbnail (I use Cura and PrusaSlicer), why not if possible? I really like the look and feel of DWC, with that I would just love it more! :)

### Describe alternatives you've considered

Ex. A workaround exists but it is tedius, for example...

### Provide any additional context or information.

Like this:
![image](https://user-images.githubusercontent.com/76131447/130374710-b92d1115-7ed1-4833-b2f3-cd4dfa635d5e.png)

**Comment by chrishamm** [comment]
Now implemented in 3.4-rc1.
