### ISSUE TITLE
[Feature Request] Plugins To level Menu Item

### ISSUE THREAD

**Issue by T3P3** [Duet3D/DuetWebControl#407]
As plugins become more numerous it would be good it they lived in there own top level menu section, rather than in settings. 
a mockup:
![image](https://user-images.githubusercontent.com/1642947/155521188-1e4a5c4a-0a97-4c1d-a874-71a11a49a3d6.png)

what is currently shown then you click on "plugins" should be the first menu item in the "plugins" section (for plugin management.

**Comment by chrishamm** [comment]
Done in v3.5-dev.
