### ISSUE TITLE
[FeatureRequest]: Firmware update process when 3rd party plugins installed.

### ISSUE THREAD

**Issue by MintyTrebor** [Duet3D/DuetWebControl#410]
### Is your feature request related to a problem? Please describe.

3rd Party plugins that do not version match to version being installed may cause issues as they are left active.

### Describe the solution you propose.

Notify the users if they have 3rd party plugins enabled that do not match the version being installed, and then offer them a choice to continue updating or not. If they choose to continue, then the incompatible plugins should be automatically stopped, requiring the user to actively turn them back on again manually

**Comment by chrishamm** [comment]
The latest version of DWC 3.5 disables invalid plugins automatically and displays a warning/error in case they could not be loaded. That change was part of making the DWC plugin loading mechanism asynchronous, which also makes the UI quicker to use on connect.
