### ISSUE TITLE
[FeatureRequest]: Additional decimal places for coordinate displays

### ISSUE THREAD

**Issue by MZachmann** [Duet3D/DuetWebControl#414]
### Is your feature request related to a problem? Please describe.

Ex. I'm always frustrated when...
Having 1 decimal place is nice for a 3d printer, but for higher accuracy devices, like CNC mills, it's just inadequate. I spend a huge amount of time doing things slowly and typing M114 and copying console output when I'd rather just look at the display. The display has plenty of room for more decimal places.

Even for speed, I like to watch the actual speeds during jobs but when a job's average speed is 4mm/s it's important to have a decimal point.

 I think if you examine CNC-specific applications they show 3 or 4 decimals default.

### Describe the solution you propose.

Ex. It would be great if...
I would really like an option to set the number of visible decimal places in the Machine and Workspace coordinate displays. Preferably, 1 on my 3d printer, 2 or 3 on my CNC, and 2, 3 or 4 on my mill - so variable.

I've coded one solution and will clean it up and attempt a pull request in the next day unless told otherwise.

### Describe alternatives you've considered

Ex. A workaround exists but it is tedius, for example...
There are no workarounds.

### Provide any additional context or information.

Ex. Photos, mockups, etc.
In the Settings / General / Appearance tab
![image](https://user-images.githubusercontent.com/3911249/162449464-9124234b-94f4-4e26-bb71-6b1bb37c80d2.png)

**Comment by chrishamm** [comment]
I agree, one decimal place isn't sufficient for CNC applications. In the next DWC version I'll show three decimal places for all visible axes instead.

If you're willing to rebuild DWC for now, you can already increase the number of displayed decimal places for non-Z axes by changing the `1` to `3` here: https://github.com/Duet3D/DuetWebControl/blob/master/src/components/panels/CNCAxesPosition.vue#L67 The Z position should already have three decimal places.

**Comment by chrishamm** [comment]
The corresponding PR has been merged, so I am closing this.
