### ISSUE TITLE
[FeatureRequest]: Option to see Inches

### ISSUE THREAD

**Issue by MZachmann** [Duet3D/DuetWebControl#415]
### Is your feature request related to a problem? Please describe.

Ex. I'm always frustrated when...
Being a US guy I grew up with imperial units and around here almost all hardware and supplies come as inches and feet so we kinda get used to it. Almost all of my manufacturing steps are done in imperial units and most of my wood designs.

Anyway, I just want a way to see coordinates and speeds in inches instead of mm - sometimes.

### Describe the solution you propose.

Ex. It would be great if...
I'd like a button in settings to just select mm/in for display. I don't need it to do anything but that. Commands are still interpreted in stream depending on the gcode unit setting.

* I have working code for this that I'm going to do a pull request in the next day unless you say otherwise.

### Describe alternatives you've considered

Ex. A workaround exists but it is tedius, for example...
There just is no real workaround.

[_note_] I hate to be pedantic but it's not '_tedius_' but is '_tedious_'

### Provide any additional context or information.

Ex. Photos, mockups, etc.
![image](https://user-images.githubusercontent.com/3911249/162466274-2aa6b7d1-cb75-4223-98f6-a4c2fec83451.png)

**Comment by chrishamm** [comment]
Closing because of related PR.
