### ISSUE TITLE
[FeatureRequest]: flowrate monitoring

### ISSUE THREAD

**Issue by cparu** [Duet3D/DuetWebControl#423]
### Is your feature request related to a problem? Please describe.

I would like to be able to see what is the current flowrate (mm3/s of filament) that the extruder is extruding, which can be also useful for troubleshooting problems and to increase the printing speed without having to calculate if the extruder is capable of extruding the filament at the new rate. 

### Describe the solution you propose.

Ex. It would be great if there will be the flowrate value on the right of the "drive0 position", inside the "status"table, in the "Extruder drives" row

### Describe alternatives you've considered

Ex. A workaround exists but it is tedius, for example...
using a calcualtor

### Provide any additional context or information.

Ex. Photos, mockups, etc.
![Screenshot 2022-06-19 at 21 54 57](https://user-images.githubusercontent.com/60483064/174498162-7595a5f7-9f57-4e51-820a-60bc052a02cf.png)

**Comment by chrishamm** [comment]
Implemented in v3.5-b1.
