### ISSUE TITLE
[FeatureRequest]: vue-i18n Automatically load browser language

### ISSUE THREAD

**Issue by ningjiazun** [Duet3D/DuetWebControl#424]
### Is your feature request related to a problem? Please describe.

vue-i18n implements automatic language switching according to the browser

### Describe the solution you propose.
https://blog.csdn.net/weixin_46034375/article/details/109110547

https://blog.logrocket.com/advanced-localization-techniques-vue-js/

### Describe alternatives you've considered

Ex. A workaround exists but it is tedius, for example...

### Provide any additional context or information.

Ex. Photos, mockups, etc.

**Comment by ningjiazun** [comment]
https://blog.csdn.net/qq_42740797/article/details/118962751

**Comment by chrishamm** [comment]
Implemented in v3.5-dev.
