### ISSUE TITLE
[FeatureRequest]: 3d CNC gcode viewer

### ISSUE THREAD

**Issue by Marshalldog** [Duet3D/DuetWebControl#426]
### Is your feature request related to a problem? Please describe.

I'm running a duet 3hc in sbc mode with raspberry pi for a cnc
I would like to be able to preview the gcode in a 3d space within the web UI (like linux cnc).
eg.
[https://www.researchgate.net/figure/The-touch-screen-optimized-GUI-of-the-Linux-CNC-interfaces_fig1_313271524](url)

### Describe the solution you propose.

Ex. It would be great if...

### Describe alternatives you've considered

Ex. A workaround exists but it is tedius, for example...

### Provide any additional context or information.

Ex. Photos, mockups, etc.

**Comment by chrishamm** [comment]
This is already supported. Check the General -> Plugins page and enable the G-code viewer there. You can then preview G-code jobs using the right-click context menu on the Files -> Job page.
