### ISSUE TITLE
[Bug]: Cannot print a file with a single quote in the name

### ISSUE THREAD

**Issue by pfn** [Duet3D/DuetWebControl#435]
### Duet Forum Discussion Thread

https://forum.duet3d.com/topic/30305/cannot-print-a-file-containing-single-quotes-from-dwc

### Which Duet products are you using?

- [X] Duet2-Wifi
- [ ] Duet2-Ethernet
- [ ] Duet Expansion Breakout Board
- [ ] Duex2
- [ ] Duex5
- [ ] Duet2-Maestro
- [ ] Maestro Dual Driver Expansion
- [X] Duet3-6HC
- [ ] Duet3-3HC
- [ ] Duet3-1XD
- [ ] Duet3-1LC
- [ ] Duet3-Tool Distribution Board
- [X] Duet3-Mini5+
- [ ] Duet3-Mini2+
- [ ] Raspberry Pi or other SBC
- [ ] SmartEffector
- [ ] Magnetic Filament Sensor
- [ ] Laser Filament Sensor
- [ ] PT100 Daughterboard
- [ ] Thermocouple Daughterboard
- [ ] PanelDue
- [ ] Other
- [ ] None

### Firmware Version

3.4.0

### Duet Web Control Version

3.4.0

### Are you using a Single Board Computer (RaspberryPi) with your Duet?

- [ ] Yes I use a SBC.
- [X] No I do not use a SBC.

### What happened?

Expected result

Can print files containing single quotes from DWC

Observed result

RRF responds with a file not found error and the single-quote is stripped out, the subsequent letter is lowercased if it is upper-cased

Steps to reproduce

Try printing any file containing single quotes from DWC's jobs tab.

This is caused by https://docs.duet3d.com/en/User_manual/Reference/Gcodes#quoted-strings which removes single quotes.
code reference https://github.com/Duet3D/RepRapFirmware/blob/3.4-dev/src/GCodes/GCodeBuffer/StringParser.cpp#L1384

**Comment by x0rtrunks** [comment]
Thanks for the report. This should be solved in 3.5.
