### ISSUE TITLE
When moving files, allow files to be overwritten after prompt

### ISSUE THREAD

**Issue by chrishamm** [Duet3D/DuetWebControl#472]
See https://forum.duet3d.com/topic/32425/dwc-allow-file-overwrite-during-move/5

**Comment by CCS86** [comment]
Hi @chrishamm is this improvement going to make it into 3.5.0 final?

**Comment by chrishamm** [comment]
No, this is planned for v3.6 (see assigned milestone).

**Comment by chrishamm** [comment]
This will be part of the next beta.
