### ISSUE TITLE
Lock scroll bars on mobile

### ISSUE THREAD

**Issue by T3P3** [Duet3D/DuetWebControl#495]
Users may inadvertently modify various values (flow rate, feed rate, fan speed) that are controlled by scroll bars in mobile view. This can lead to issues with the printed part.

Adding t lock feature in this mode would prevent this. To modify them, users need to explicitly unlock them, and they automatically re-lock after a few seconds.

A global override in the settings to not lock, and change the timeout for lock would also be good.

**Comment by chrishamm** [comment]
My new implementation auto-locks sliders in mobile view. It requires corresponding sliders to be unlocked using a click, but they do not auto-lock again at this point. There is no global override for this yet.
